name: Build and Run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install cppcheck static analysis
      run: sudo apt-get update && sudo apt-get install -y cppcheck
      
    - name: static analysis
      run: cppcheck --suppress=missingIncludeSystem --check-config --force --enable=all --error-exitcode=1 .
      
    - name: Sender build
      run: g++ -Wall -Wextra -Werror --coverage -o SenderExe  CaseStudy/Sender/*.cpp
      
    - name: SenderTest build
      run: g++ -Wall -Wextra -Werror --coverage -o SenderTestExe  CaseStudy/SenderTest/*.cpp

    - name: run SenderTest
      run: ./SenderTestExe 
      
    - name: Sender-Test coverage report
      run: gcov -r SenderTest.cpp
