name: Limit complexity

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install lizard
      run: pip install lizard

    - name: Limit complexity
      run: $HOME/.local/bin/lizard --CCN 3 -x"./CaseStudy/SenderTest/catch.hpp" -x"./CaseStudy/ReceiverTest/catch.hpp"
